vaadin.launch-browser=true
spring.application.name=talk-tracker

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3.5:0.8b