vaadin.launch-browser=true
spring.application.name=talk-tracker

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

spring.ai.openai.api-key=${OPENAI_API_KEY}